server:
    port: 80
    servlet:
        context-path: /

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_blog12345
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true 
    thymeleaf:
        cache: false
        
blogImgPath: E://my_project/Blog/src/main/webapp/static/upload/blogImg/
blogImgUrl: /static/upload/blogImg/
    